// "Hot Module Replacement" enabled environment

export const environment = {
    production: false,
    apiServerBaseUrl: 'https://iris-b2c-api-stage.azurewebsites.net/api/services/',
    apiPlatformBaseUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/',
    apiPlatformUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/api/services/',
    apiSocialBaseUrl: '',
    apiSocialServiceBaseUrl: '',
    apiAnalyticsBaseUrl: '',
    apiAnalyticsServiceBaseUrl: '',
    hmr: false,
    appConfig: 'appconfig.b2cstaging.json',
    isB2CInstance: true,
    instance1EnabledTenant: '',
    instance2EnabledTenant: '',
    instance3EnabledTenant: '',
    azureFunctionEndPoint: '',

    // SSO -> OIDC Client configurations
    authority: 'https://iris-b2c-idp-stage.azurewebsites.net/',
    client_id: 'angular',
    redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/auth-callback',
    post_logout_redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/',
    response_type: "code",
    scope: "openid profile default-api",
    filterProtocolClaims: true,
    loadUserInfo: true,

    instance1: {
        appConfig: 'appconfig.b2cstaging.json',
        apiServerBaseUrl: 'https://iris-b2c-api-stage.azurewebsites.net/api/services/',
        apiPlatformBaseUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        apiPlatformUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/api/services/',
        apiSocialBaseUrl: '',
        apiSocialServiceBaseUrl: '',
        apiAnalyticsBaseUrl: '',
        apiAnalyticsServiceBaseUrl: '',

        // SSO -> OIDC Client configurations for second instance
        authority: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        client_id: 'angular',
        redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/auth-callback',
        post_logout_redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/',
        response_type: "code",
        scope: "openid profile default-api",
        filterProtocolClaims: true,
        loadUserInfo: true,
        azureFunctionEndPoint: '',
    },

    instance2: {
        appConfig: 'appconfig.b2cstaging.json',
        apiServerBaseUrl: 'https://iris-b2c-api-stage.azurewebsites.net/api/services/',
        apiPlatformBaseUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        apiPlatformUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/api/services/',
        apiSocialBaseUrl: '',
        apiSocialServiceBaseUrl: '',
        apiAnalyticsBaseUrl: '',
        apiAnalyticsServiceBaseUrl: '',

        // SSO -> OIDC Client configurations for third instance
        authority: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        client_id: 'angular',
        redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/auth-callback',
        post_logout_redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/',
        response_type: "code",
        scope: "openid profile default-api",
        filterProtocolClaims: true,
        loadUserInfo: true,
        azureFunctionEndPoint: '',
    },

    instance3: {
        appConfig: 'appconfig.b2cstaging.json',
        apiServerBaseUrl: 'https://iris-b2c-api-stage.azurewebsites.net/api/services/',
        apiPlatformBaseUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        apiPlatformUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/api/services/',
        apiSocialBaseUrl: '',
        apiSocialServiceBaseUrl: '',
        apiAnalyticsBaseUrl: '',
        apiAnalyticsServiceBaseUrl: '',
        // SSO -> OIDC Client configurations for fourth instance
        authority: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        client_id: 'angular',
        redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/auth-callback',
        post_logout_redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/',
        response_type: "code",
        scope: "openid profile default-api",
        filterProtocolClaims: true,
        loadUserInfo: true,
        azureFunctionEndPoint: '',
    },
    instance4: {
        appConfig: 'appconfig.b2cstaging.json',
        apiServerBaseUrl: 'https://iris-b2c-api-stage.azurewebsites.net/api/services/',
        apiPlatformBaseUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        apiPlatformUrl: 'https://iris-b2c-idp-stage.azurewebsites.net/api/services/',
        apiSocialBaseUrl: '',
        apiSocialServiceBaseUrl: '',
        apiAnalyticsBaseUrl: '',
        apiAnalyticsServiceBaseUrl: '',
        // SSO -> OIDC Client configurations for fourth instance
        authority: 'https://iris-b2c-idp-stage.azurewebsites.net/',
        client_id: 'angular',
        redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/auth-callback',
        post_logout_redirect_uri: 'https://iris-b2c-ui-stage.azurewebsites.net/',
        response_type: "code",
        scope: "openid profile default-api",
        filterProtocolClaims: true,
        loadUserInfo: true,
        azureFunctionEndPoint: '',
    }
};
